// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sannel.Encoding.Manager.Web.Features.Data;

#nullable disable

namespace Sannel.Encoding.Manager.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419223752_Jellyfin")]
    partial class Jellyfin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinDestinationRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("JellyfinDestinationRoots");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDestination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SftpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JellyfinServers");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinSyncProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerBId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIdA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerAId");

                    b.HasIndex("ServerBId");

                    b.ToTable("JellyfinSyncProfiles");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Queue.Entities.EncodeQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioDefault")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentTrackProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscRootLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncodingCommandsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JellyfinDestRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JellyfinDestRootId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JellyfinDestServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinSourceItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JellyfinSourceServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinUploadStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunnerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TracksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TvdbShowName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EncodeQueueItems");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Queue.Entities.EncodingPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EncodingPresets");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Runner.Entities.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentJobId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Scan.Entities.DiscScanCache", b =>
                {
                    b.Property<string>("InputPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InputPath");

                    b.ToTable("DiscScanCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Settings.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioDefault")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTrackDestinationTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackDestinationRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackDestinationTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TvdbLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Tvdb.Entities.TvdbEpisodeCache", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderType")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId", "OrderType", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("TvdbEpisodeCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Tvdb.Entities.TvdbSeriesCache", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId");

                    b.ToTable("TvdbSeriesCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinDestinationRoot", b =>
                {
                    b.HasOne("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinSyncProfile", b =>
                {
                    b.HasOne("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinServer", "ServerA")
                        .WithMany()
                        .HasForeignKey("ServerAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sannel.Encoding.Manager.Web.Features.Jellyfin.Entities.JellyfinServer", "ServerB")
                        .WithMany()
                        .HasForeignKey("ServerBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServerA");

                    b.Navigation("ServerB");
                });
#pragma warning restore 612, 618
        }
    }
}
