// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sannel.Encoding.Manager.Web.Features.Data;

#nullable disable

namespace Sannel.Encoding.Manager.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Queue.Entities.EncodeQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioDefault")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TracksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TvdbShowName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EncodeQueueItems");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Queue.Entities.EncodingPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EncodingPresets");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Scan.Entities.DiscScanCache", b =>
                {
                    b.Property<string>("InputPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InputPath");

                    b.ToTable("DiscScanCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Settings.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioDefault")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackDestinationRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackDestinationTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Tvdb.Entities.TvdbEpisodeCache", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderType")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId", "OrderType", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("TvdbEpisodeCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Tvdb.Entities.TvdbSeriesCache", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId");

                    b.ToTable("TvdbSeriesCache");
                });
#pragma warning restore 612, 618
        }
    }
}
