// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sannel.Encoding.Manager.Web.Features.Data;

#nullable disable

namespace Sannel.Encoding.Manager.Migrations.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004031253_AddMcpSupport")]
    partial class AddMcpSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.DiscMenu.Entities.DiscMenuCache", b =>
                {
                    b.Property<string>("InputPath")
                        .HasColumnType("text");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("character varying(48)");

                    b.Property<string>("DiscType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MenuJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProbeVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScreenshotFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InputPath");

                    b.ToTable("DiscMenuCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Mcp.Entities.UserApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("character varying(48)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastUsedAt")
                        .HasColumnType("character varying(48)");

                    b.Property<string>("UserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserObjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserPrincipalName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserObjectId")
                        .IsUnique();

                    b.ToTable("UserApiKeys");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Queue.Entities.EncodeQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioDefault")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("character varying(48)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("character varying(48)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByObjectId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedVia")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentTrackProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("DiscPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscRootLabel")
                        .HasColumnType("text");

                    b.Property<string>("EncodingCommandsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("RunnerName")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StartedAt")
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TracksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<string>("TvdbShowName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EncodeQueueItems");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Queue.Entities.EncodingPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EncodingPresets");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Runner.Entities.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentJobId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSeenAt")
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Scan.Entities.DiscScanCache", b =>
                {
                    b.Property<string>("InputPath")
                        .HasColumnType("text");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("character varying(48)");

                    b.Property<string>("ScanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InputPath");

                    b.ToTable("DiscScanCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Settings.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioDefault")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudioLanguages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovieTrackDestinationTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubtitleLanguages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackDestinationRoot")
                        .HasColumnType("text");

                    b.Property<string>("TrackDestinationTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TvdbLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Tvdb.Entities.TvdbEpisodeCache", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("OrderType")
                        .HasColumnType("text");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SeriesId", "OrderType", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("TvdbEpisodeCache");
                });

            modelBuilder.Entity("Sannel.Encoding.Manager.Web.Features.Tvdb.Entities.TvdbSeriesCache", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("CachedAt")
                        .IsRequired()
                        .HasColumnType("character varying(48)");

                    b.Property<string>("LastAccessedAt")
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.HasKey("SeriesId");

                    b.ToTable("TvdbSeriesCache");
                });
#pragma warning restore 612, 618
        }
    }
}
